services:
  sat-gui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sat-gui
    ports:
      - "8000:8000"
    volumes:
      - ./config:/app/config
      - ./fiel-uploads:/app/fiel-uploads
      - ./descargas:/app/descargas
      - ./reportes:/app/reportes
      - ./storage:/app/storage
    restart: unless-stopped
